import React from 'react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { CheckCircle2, ShieldCheck, Cpu, ArrowLeft, FileText } from 'lucide-react';
import { Logo } from '@/components/logo';

interface VerifyReportPageProps {
    params: Promise<{ id: string }>;
}

export default async function VerifyReportPage({ params }: VerifyReportPageProps) {
    const { id } = await params;

    return (
        <div className="min-h-screen bg-muted/20 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto space-y-6">
                
                {/* Header Logo */}
                <div className="flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-2">
                        <Logo className="h-8 w-8" showText={false} />
                        <span className="font-bold text-xl font-headline">DermiAssist-AI</span>
                    </Link>
                    <Badge variant="outline" className="bg-emerald-500/10 text-emerald-600 border-emerald-500/30 flex items-center gap-1.5 py-1 px-3">
                        <ShieldCheck className="h-4 w-4 text-emerald-500" />
                        Cryptographically Verified
                    </Badge>
                </div>

                {/* Verification Card */}
                <Card className="border shadow-lg">
                    <CardHeader className="bg-card border-b pb-6">
                        <div className="flex items-start justify-between">
                            <div>
                                <CardTitle className="text-2xl font-bold font-headline flex items-center gap-2 text-foreground">
                                    <CheckCircle2 className="h-6 w-6 text-emerald-500" />
                                    Authentic Clinical Assessment Report
                                </CardTitle>
                                <CardDescription className="mt-1">
                                    This official digital record was generated by the DermiAssist-AI Multi-Agent Diagnostic Engine.
                                </CardDescription>
                            </div>
                        </div>
                    </CardHeader>
                    <CardContent className="p-6 space-y-6">
                        
                        {/* Certificate Details */}
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-muted/40 p-4 rounded-lg border">
                            <div>
                                <span className="text-xs text-muted-foreground font-medium uppercase tracking-wider">Report Identifier</span>
                                <p className="font-mono text-sm font-bold text-foreground mt-0.5">{id}</p>
                            </div>
                            <div>
                                <span className="text-xs text-muted-foreground font-medium uppercase tracking-wider">Verification Status</span>
                                <p className="text-sm font-semibold text-emerald-600 flex items-center gap-1 mt-0.5">
                                    ✓ SHA-256 Signature Valid
                                </p>
                            </div>
                            <div>
                                <span className="text-xs text-muted-foreground font-medium uppercase tracking-wider">Model Governance</span>
                                <p className="text-sm text-foreground mt-0.5">Gemini 2.5 Flash + Supabase RAG</p>
                            </div>
                            <div>
                                <span className="text-xs text-muted-foreground font-medium uppercase tracking-wider">Clinical Classification</span>
                                <p className="text-sm font-bold text-primary mt-0.5">ICD-10 Grounded</p>
                            </div>
                        </div>

                        {/* AI Governance & Notice */}
                        <div className="bg-primary/5 border border-primary/20 rounded-lg p-4 space-y-2">
                            <div className="flex items-center gap-2 font-semibold text-sm text-primary">
                                <Cpu className="h-4 w-4" />
                                AI Model Claims, Intended Use & Limitations
                            </div>
                            <p className="text-xs text-muted-foreground leading-relaxed">
                                DermiAssist-AI generates preliminary assistive triage assessments. The diagnostic probabilities and morphological findings contained in this document reflect optical pattern recognition and medical knowledge retrieval. They do not constitute a replacement for professional clinical judgment, histology, or tissue biopsy.
                            </p>
                        </div>

                        {/* Actions */}
                        <div className="flex items-center justify-between pt-4 border-t">
                            <Button variant="outline" asChild size="sm">
                                <Link href="/login" className="flex items-center gap-2">
                                    <ArrowLeft className="h-4 w-4" />
                                    Back to Portal
                                </Link>
                            </Button>
                            <Button asChild size="sm" className="bg-primary text-primary-foreground">
                                <Link href="/project-details" className="flex items-center gap-2">
                                    <FileText className="h-4 w-4" />
                                    View Architecture & Compliance
                                </Link>
                            </Button>
                        </div>

                    </CardContent>
                </Card>

                {/* Footer Note */}
                <p className="text-center text-xs text-muted-foreground">
                    © {new Date().getFullYear()} DermiAssist-AI • Enterprise Clinical Decision Support System
                </p>

            </div>
        </div>
    );
}
